echo "We are trying this practical from linux EC2"
echo "We are from batch-30 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Devops"
echo "we are leaning mergerconflict topic"
echo "we are leaning mergerconflict topics"
